### ISSUE TITLE
Toggle doesn't work from terminal mode

### ISSUE THREAD

**Issue by poetaman** [fannheyward/coc-terminal#58]
Toggle works to open terminal, but not to close it. Here are the mappings I used:

```
nmap <C-s> <Plug>(coc-terminal-toggle)
tmap <C-s> <Plug>(coc-terminal-toggle)
```

Also, a reason this doesn't work with nnoremap/ tnoremap?

**Comment by fannheyward** [comment]
No terminal mode mappings in coc/coc-terminal by now.

**Comment by riza-khan** [comment]
I am unable to move my target buffer to another one, is this intentional?

<img width="1440" alt="2021-09-15_16-03-54" src="https://user-images.githubusercontent.com/86204577/133501767-927f8eee-5c01-4188-8559-9281f9659497.png">


EDIT:

https://github.com/fannheyward/coc-terminal/issues/52#issuecomment-753713460 works like a charm! Issue can remained closed.
